Got it!

diff --git a/.github/workflows/examples.yml b/.github/workflows/examples.yml
--- a/.github/workflows/examples.yml
+++ b/.github/workflows/examples.yml
@@ -40,6 +40,8 @@ jobs:
     - uses: hashicorp/setup-terraform@v1
       with:
         terraform_version: ${{ matrix.terraform_version }}
+        # Needed to use the output of `terraform validate -json`
+        terraform_wrapper: false
     - name: terraform
       run: |
         for DIR in $(find ./examples -type f -name '*.tf' -exec dirname {} \; | sort -u); do
@@ -54,5 +56,10 @@ jobs:
           echo; echo -e "\e[1;35m===> Validating Example: $DIR <===\e[0m"; echo
           # Catch errors
           terraform validate
+          # Check for warnings. For simplicity, assume warnings are related to pre-0.12 syntax
+          if [ "$(terraform validate -json | jq -r '.warning_count')" != '0' ]; then
+            echo -e "\e[1;31mError:\e[0m Configuration contains warnings."
+            exit 1
+          fi
           popd
         done
