Resetting warning test to debug it

diff --git a/.github/workflows/examples.yml b/.github/workflows/examples.yml
--- a/.github/workflows/examples.yml
+++ b/.github/workflows/examples.yml
@@ -54,10 +54,10 @@ jobs:
           echo; echo -e "\e[1;35m===> Validating Example: $DIR <===\e[0m"; echo
           # Catch errors
           terraform validate
-          # Check for warnings. For simplicity, assume warnings are related to pre-0.12 syntax
-          if [ "$(terraform validate -json | jq -r '.warning_count')" != '0' ]; then
-            echo -e "\e[1;31mError:\e[0m Configuration contains warnings."
-            exit 1
-          fi
+          # # Check for warnings. For simplicity, assume warnings are related to pre-0.12 syntax
+          # if [ "$(terraform validate -json | jq -r '.warning_count')" != '0' ]; then
+          #   echo -e "\e[1;31mError:\e[0m Configuration contains warnings."
+          #   exit 1
+          # fi
           popd
         done
